import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>BAKEWELL-WHITE</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/Logo.svg" />
			</Head>
			<div className="hero">
				<div className="heroContent flex content-center">
					<Image
						alt="big logo"
						src="/LogoLarge.svg"
						height={350}
						width={1000}
						layout="intrinsic"
					/>
					<ul className="caption contact">
						<li className="caption">
							+64 9 480 6800 <br /> INFO@BAKEWELL-WHITE@GMAIL.COM
						</li>
						<li>
							BAKEWELL-WHITE YACHT DESIGN LTD <br /> PACE WITH GRACE /
							BAKEWELL-WHITE &copy; 2022
						</li>
						<li>
							EST. 1994
							<br />
							AUCKLAND / NEW ZEALAND
						</li>
					</ul>
				</div>
			</div>
			<div className="frame2">
				<div className="frame2Boat"></div>
			</div>
		</div>
	)
}

export default Home
